insert into model_route (
    id,
    model_alias,
    capability,
    deployment_code,
    priority,
    enabled,
    created_at
) values (
    'dafb75e2-6f66-4bf7-88c9-9e1eb1269644',
    'text.audio-transcription-postprocess',
    'TEXT_GENERATION',
    'zhipu-glm-4-5-air-text',
    10,
    true,
    now()
)
on conflict (model_alias, capability, deployment_code) do update
set priority = excluded.priority,
    enabled = excluded.enabled;

insert into feature_definition (
    id,
    workspace_id,
    code,
    display_name,
    description,
    status,
    current_version,
    result_type,
    renderer_key,
    execution_mode,
    sort_order,
    created_at,
    updated_at
)
select
    '42c19d13-c77f-44e3-9e37-64857e9bbf2c',
    workspace.id,
    'audio.transcription',
    '音频转写',
    '将单个预录音频转换为带可选说话人和分段时间戳的可读逐字稿，并可生成摘要或会议纪要。',
    'INTERNAL',
    1,
    'transcript',
    'transcript',
    'ASYNC',
    10,
    now(),
    now()
from workspace
where workspace.code = 'audio';

insert into feature_version (
    id,
    feature_id,
    version,
    input_schema_json,
    ui_schema_json,
    output_schema_json,
    config_json,
    created_at
) values (
    '9e82f791-19e4-412e-81bb-177c9640ba44',
    '42c19d13-c77f-44e3-9e37-64857e9bbf2c',
    1,
    $json$
    {
      "$schema":"https://json-schema.org/draft/2020-12/schema",
      "type":"object",
      "required":["audioFile","language","speakerDiarization","timestampMode","postProcess"],
      "properties":{
        "audioFile":{
          "type":"string",
          "format":"uuid",
          "title":"音频文件",
          "description":"每次转写一个预录音频，建议时长不超过 2 小时。"
        },
        "language":{
          "type":"string",
          "const":"auto",
          "default":"auto",
          "title":"识别语言"
        },
        "speakerDiarization":{
          "type":"boolean",
          "default":false,
          "title":"区分说话人",
          "description":"自动将不同发言者标记为说话人 A、B、C。"
        },
        "timestampMode":{
          "type":"string",
          "enum":["segment","none"],
          "default":"segment",
          "title":"时间戳",
          "description":"按发言段显示开始时间，或隐藏时间信息。"
        },
        "postProcess":{
          "type":"string",
          "enum":["none","summary","meeting_minutes"],
          "default":"none",
          "title":"附加结果",
          "description":"逐字稿始终生成，可额外整理摘要或会议纪要。"
        },
        "professionalTerms":{
          "type":"string",
          "maxLength":4000,
          "title":"专业词提示",
          "description":"可选。使用逗号、分号或换行分隔人名、产品名和专业术语。"
        }
      },
      "additionalProperties":false
    }
    $json$::jsonb,
    $json$
    {
      "order":[
        "audioFile",
        "language",
        "speakerDiarization",
        "timestampMode",
        "postProcess",
        "professionalTerms"
      ],
      "widgets":{
        "audioFile":"audio",
        "language":"hidden",
        "speakerDiarization":"switch",
        "timestampMode":"segmented",
        "postProcess":"segmented",
        "professionalTerms":"textarea"
      },
      "enumLabels":{
        "timestampMode":{
          "segment":"分段时间",
          "none":"不显示"
        },
        "postProcess":{
          "none":"不生成",
          "summary":"摘要",
          "meeting_minutes":"会议纪要"
        }
      },
      "fieldOptions":{
        "audioFile":{
          "acceptedMimeTypes":[
            "audio/mpeg",
            "audio/mp3",
            "audio/aac",
            "audio/mp4",
            "audio/x-m4a",
            "audio/wav",
            "audio/x-wav",
            "audio/flac",
            "audio/x-flac",
            "audio/ogg",
            "application/ogg",
            "application/octet-stream"
          ],
          "allowedExtensions":[".mp3",".aac",".m4a",".wav",".flac",".ogg"],
          "maxItems":1,
          "maxFileSizeBytes":209715200,
          "maxTotalSizeBytes":209715200,
          "allowAssetLibrarySelection":true,
          "uploadLabel":"选择并上传音频"
        },
        "timestampMode":{
          "showSelectedIcon":false,
          "compact":true,
          "labelMaxLines":1
        },
        "postProcess":{
          "showSelectedIcon":false,
          "compact":true,
          "labelMaxLines":1
        }
      },
      "fieldHelp":{
        "audioFile":{
          "text":"支持 MP3、AAC、M4A、WAV、FLAC 和 OGG，单文件不超过 200 MB。"
        },
        "professionalTerms":{
          "text":"最多 200 项；单项不超过 60 个字符或 6 个空格分隔词。"
        }
      },
      "feeNotice":"音频转写会调用付费音频模型；选择摘要或会议纪要时会额外调用文本模型。点击“开始转写”即表示确认本次调用。",
      "submitLabel":"开始转写",
      "revisionSubmitLabel":"生成新版本"
    }
    $json$::jsonb,
    $json$
    {
      "$schema":"https://json-schema.org/draft/2020-12/schema",
      "type":"object",
      "required":[
        "text",
        "segments",
        "detectedLanguage",
        "speakerDiarization",
        "timestampMode",
        "postProcess"
      ],
      "properties":{
        "text":{"type":"string","minLength":1},
        "segments":{
          "type":"array",
          "items":{"$ref":"#/$defs/segment"}
        },
        "detectedLanguage":{"type":["string","null"]},
        "speakerDiarization":{"type":"boolean"},
        "timestampMode":{
          "type":"string",
          "enum":["segment","none"]
        },
        "postProcess":{
          "type":"string",
          "enum":["none","summary","meeting_minutes"]
        },
        "supplement":{"$ref":"#/$defs/supplement"}
      },
      "$defs":{
        "segment":{
          "type":"object",
          "required":["startMs","endMs","text"],
          "properties":{
            "startMs":{"type":"integer","minimum":0},
            "endMs":{"type":"integer","minimum":0},
            "text":{"type":"string","minLength":1},
            "speaker":{"type":["string","null"]},
            "confidence":{
              "type":["number","null"],
              "minimum":0,
              "maximum":1
            }
          },
          "additionalProperties":false
        },
        "supplement":{
          "type":"object",
          "required":["type","status","format"],
          "properties":{
            "type":{
              "type":"string",
              "enum":["summary","meeting_minutes"]
            },
            "status":{
              "type":"string",
              "enum":["SUCCEEDED","FAILED"]
            },
            "format":{"const":"markdown"},
            "text":{"type":"string"},
            "errorCode":{"type":"string"}
          },
          "additionalProperties":false
        }
      },
      "additionalProperties":false
    }
    $json$::jsonb,
    $json$
    {
      "modelAliases":{
        "AUDIO_TRANSCRIPTION":"audio.transcription.default",
        "TEXT_GENERATION":"text.audio-transcription-postprocess"
      },
      "maxInputFiles":1,
      "maxInputFileBytes":209715200,
      "supportedDurationTargetSeconds":7200,
      "maxProfessionalTerms":200,
      "maxProfessionalTermsCharacters":4000,
      "taskTitleFromAssets":{
        "field":"audioFile",
        "template":"{name} 转写"
      },
      "capabilities":["AUDIO_TRANSCRIPTION","TEXT_GENERATION"]
    }
    $json$::jsonb,
    now()
);

insert into feature_model_policy (
    id,
    feature_code,
    capability,
    default_deployment_code,
    allow_user_selection,
    created_at,
    updated_at
) values
    (
        '225a7f97-caf2-4ce4-8341-3fd0261de22b',
        'audio.transcription',
        'AUDIO_TRANSCRIPTION',
        'assemblyai-universal-3-5-pro-audio',
        true,
        now(),
        now()
    ),
    (
        '8d111140-e9d4-48b9-a6b0-04082aace4b2',
        'audio.transcription',
        'TEXT_GENERATION',
        'zhipu-glm-4-5-air-text',
        false,
        now(),
        now()
    );

insert into feature_model_option (
    policy_id,
    deployment_code,
    display_name,
    description,
    sort_order,
    enabled
) values
    (
        '225a7f97-caf2-4ce4-8341-3fd0261de22b',
        'assemblyai-universal-3-5-pro-audio',
        'AssemblyAI Universal-3.5 Pro',
        '高准确率转写模型，支持自动语言识别、说话人区分和专业词提示。',
        10,
        true
    ),
    (
        '225a7f97-caf2-4ce4-8341-3fd0261de22b',
        'assemblyai-universal-2-audio',
        'AssemblyAI Universal-2',
        '成本更低的通用转写模型，适合常规录音整理。',
        20,
        true
    ),
    (
        '8d111140-e9d4-48b9-a6b0-04082aace4b2',
        'zhipu-glm-4-5-air-text',
        'GLM-4.5-Air',
        '用于将完整逐字稿整理为摘要或会议纪要。',
        10,
        true
    );
