insert into feature_definition (
    id,
    workspace_id,
    code,
    display_name,
    description,
    status,
    current_version,
    result_type,
    renderer_key,
    execution_mode,
    sort_order,
    created_at,
    updated_at
)
select
    '5f1f84a9-d775-4d02-97aa-4f14d1a813b8',
    workspace.id,
    'document.data_analysis',
    '数据分析与图表',
    '分析单个 Excel 或 UTF-8 CSV 文件，输出结论、异常、静态图表和 XLSX 报告。',
    'INTERNAL',
    1,
    'data_analysis',
    'data_analysis',
    'ASYNC',
    30,
    now(),
    now()
from workspace
where workspace.code = 'document';

insert into feature_version (
    id,
    feature_id,
    version,
    input_schema_json,
    ui_schema_json,
    output_schema_json,
    config_json,
    created_at
) values (
    '5a2a5a31-44c7-4076-881b-a5d2880dabf9',
    '5f1f84a9-d775-4d02-97aa-4f14d1a813b8',
    1,
    $json$
    {
      "$schema":"https://json-schema.org/draft/2020-12/schema",
      "type":"object",
      "required":["dataFile"],
      "properties":{
        "dataFile":{
          "type":"string",
          "format":"uuid",
          "title":"数据文件",
          "description":"每次分析一个 XLS、XLSX 或 UTF-8 CSV 文件。"
        },
        "focus":{
          "type":"string",
          "maxLength":500,
          "title":"关注重点",
          "description":"可选。说明需要重点关注的指标、异常或业务问题。"
        }
      },
      "additionalProperties":false
    }
    $json$::jsonb,
    $json$
    {
      "order":["dataFile","focus"],
      "widgets":{
        "dataFile":"file",
        "focus":"textarea"
      },
      "fieldOptions":{
        "dataFile":{
          "acceptedMimeTypes":[
            "application/vnd.ms-excel",
            "application/msexcel",
            "application/x-msexcel",
            "application/x-excel",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "application/zip",
            "application/x-zip-compressed",
            "text/csv",
            "text/plain",
            "application/csv",
            "text/comma-separated-values",
            "application/octet-stream"
          ],
          "allowedExtensions":[".xls",".xlsx",".csv"],
          "maxItems":1,
          "maxFileSizeBytes":52428800,
          "maxTotalSizeBytes":52428800,
          "allowAssetLibrarySelection":true,
          "showPreview":false,
          "uploadLabel":"选择数据文件"
        }
      },
      "fieldHelp":{
        "dataFile":{
          "text":"读取全部可见工作表，公式仅使用缓存显示值。最多 20 个可见工作表、10 万行、单表 200 列和 50 万个非空单元格。CSV 仅支持 UTF-8 或 UTF-8 BOM；超限时直接失败，不会抽样或截断。"
        }
      },
      "modelSelectionGroups":[
        {
          "key":"dataAnalysisModel",
          "label":"数据分析模型",
          "description":"本地程序负责统计和图表数据，模型负责形成有证据的结论。",
          "capabilities":["TEXT_GENERATION"],
          "options":[
            {
              "value":"gpt-5.6-sol",
              "displayName":"GPT-5.6 Sol",
              "description":"默认模型，适合多工作表和复杂指标关系。",
              "deployments":{
                "TEXT_GENERATION":"codex2api-gpt-5-6-sol-text"
              }
            },
            {
              "value":"gpt-5.4-mini",
              "displayName":"GPT-5.4 Mini",
              "description":"响应更轻量，适合结构清晰的常规数据。",
              "deployments":{
                "TEXT_GENERATION":"codex2api-gpt-5-4-mini-text"
              }
            }
          ]
        }
      ],
      "feeNotice":"数据解析、统计和图表在本地完成；分析结论会调用所选付费文本模型。模型最多调用两次，第二次仅用于修复结构化结果。点击“开始分析”即表示确认本次调用。",
      "submitLabel":"开始分析",
      "revisionSubmitLabel":"重新分析"
    }
    $json$::jsonb,
    $json$
    {
      "$schema":"https://json-schema.org/draft/2020-12/schema",
      "type":"object",
      "required":[
        "format",
        "summaryMarkdown",
        "conclusions",
        "anomalies",
        "charts",
        "chartAssetIds",
        "reportAssetId",
        "reportName",
        "warnings",
        "partial"
      ],
      "properties":{
        "format":{"const":"data_analysis"},
        "summaryMarkdown":{"type":"string","minLength":1},
        "conclusions":{
          "type":"array",
          "minItems":1,
          "maxItems":10,
          "items":{
            "type":"object",
            "required":["title","detail","evidence"],
            "properties":{
              "title":{"type":"string","minLength":1},
              "detail":{"type":"string","minLength":1},
              "evidence":{"type":"array","items":{"type":"string"}}
            },
            "additionalProperties":false
          }
        },
        "anomalies":{
          "type":"array",
          "items":{
            "type":"object",
            "required":[
              "id","type","severity","sheetName","columnName",
              "description","evidence","interpretation","suggestion"
            ],
            "properties":{
              "id":{"type":"string"},
              "type":{"type":"string"},
              "severity":{"type":"string","enum":["INFO","WARNING","CRITICAL"]},
              "sheetName":{"type":"string"},
              "columnName":{"type":"string"},
              "rowNumber":{"type":"integer","minimum":1},
              "description":{"type":"string"},
              "evidence":{"type":"string"},
              "interpretation":{"type":"string"},
              "suggestion":{"type":"string"}
            },
            "additionalProperties":false
          }
        },
        "charts":{
          "type":"array",
          "minItems":1,
          "maxItems":4,
          "items":{
            "type":"object",
            "required":[
              "id","title","type","sheetName","categoryLabel",
              "valueLabel","aggregation","assetIndex"
            ],
            "properties":{
              "id":{"type":"string"},
              "title":{"type":"string"},
              "type":{"type":"string","enum":["BAR","LINE"]},
              "sheetName":{"type":"string"},
              "categoryLabel":{"type":"string"},
              "valueLabel":{"type":"string"},
              "aggregation":{"type":"string"},
              "assetIndex":{"type":"integer","minimum":0,"maximum":3}
            },
            "additionalProperties":false
          }
        },
        "chartAssetIds":{
          "type":"array",
          "minItems":1,
          "maxItems":4,
          "items":{"type":"string","format":"uuid"}
        },
        "reportAssetId":{"type":"string","format":"uuid"},
        "reportName":{"type":"string","minLength":1},
        "warnings":{"type":"array","items":{"type":"string"}},
        "partial":{"const":false}
      },
      "additionalProperties":false
    }
    $json$::jsonb,
    $json$
    {
      "modelAlias":"text.document-data-analysis",
      "maxFiles":1,
      "maxFileSizeBytes":52428800,
      "maxVisibleSheets":20,
      "maxRows":100000,
      "maxColumnsPerSheet":200,
      "maxNonEmptyCells":500000,
      "maxFocusCharacters":500,
      "minCharts":1,
      "maxCharts":4,
      "csvEncoding":"UTF-8",
      "maxModelInvocations":2,
      "capabilities":["TEXT_GENERATION"]
    }
    $json$::jsonb,
    now()
);

insert into feature_model_policy (
    id,
    feature_code,
    capability,
    default_deployment_code,
    allow_user_selection,
    created_at,
    updated_at
) values (
    '16f0d018-28b6-4935-a365-6a41b21dbafd',
    'document.data_analysis',
    'TEXT_GENERATION',
    'codex2api-gpt-5-6-sol-text',
    true,
    now(),
    now()
);

insert into feature_model_option (
    policy_id,
    deployment_code,
    display_name,
    description,
    sort_order,
    enabled
) values
    (
        '16f0d018-28b6-4935-a365-6a41b21dbafd',
        'codex2api-gpt-5-6-sol-text',
        'GPT-5.6 Sol',
        '质量优先，适合多工作表、复杂指标关系和异常解释。',
        10,
        true
    ),
    (
        '16f0d018-28b6-4935-a365-6a41b21dbafd',
        'codex2api-gpt-5-4-mini-text',
        'GPT-5.4 Mini',
        '速度和成本优先，适合结构清晰的常规数据。',
        20,
        true
    );

update workspace
set search_terms_json = search_terms_json
        || '["数据分析","图表","异常","Excel","CSV"]'::jsonb
where code = 'document';
