insert into model_route (
    id,
    model_alias,
    capability,
    deployment_code,
    priority,
    enabled,
    created_at
) values
    (
        '894bc821-0f38-4824-b130-f7832675845e',
        'text.document-compare',
        'TEXT_GENERATION',
        'codex2api-gpt-5-6-sol-text',
        10,
        true,
        now()
    ),
    (
        '0c604546-e93b-40b5-a945-7acacc8a02b9',
        'vision.document-compare',
        'VISION',
        'codex2api-gpt-5-6-sol-vision',
        10,
        true,
        now()
    )
on conflict (model_alias, capability, deployment_code) do nothing;

insert into feature_definition (
    id,
    workspace_id,
    code,
    display_name,
    description,
    status,
    current_version,
    result_type,
    renderer_key,
    execution_mode,
    sort_order,
    created_at,
    updated_at
)
select
    'a72fa01e-08ba-4936-abf5-cfc1ab029439',
    workspace.id,
    'document.compare',
    '多文档对比',
    '对比最多五份合同、制度或不同版本文档，标注差异、综合结论和风险，并提供可追溯来源。',
    'INTERNAL',
    1,
    'document_comparison',
    'document_compare',
    'ASYNC',
    30,
    now(),
    now()
from workspace
where workspace.code = 'document';

insert into feature_version (
    id,
    feature_id,
    version,
    input_schema_json,
    ui_schema_json,
    output_schema_json,
    config_json,
    created_at
) values (
    '5954e5bb-c441-45fe-abe1-1b170d773047',
    'a72fa01e-08ba-4936-abf5-cfc1ab029439',
    1,
    $json$
    {
      "$schema":"https://json-schema.org/draft/2020-12/schema",
      "type":"object",
      "required":["comparisonDocuments","comparisonMode"],
      "properties":{
        "baselineDocument":{
          "type":"string",
          "format":"uuid",
          "title":"基准文档",
          "description":"可选。上传后会分别对比每份文档，并生成跨文档综合结论。"
        },
        "comparisonDocuments":{
          "type":"array",
          "title":"对比文档",
          "description":"有基准文档时选择 1 至 4 份；无基准文档时选择 2 至 5 份。",
          "uniqueItems":true,
          "items":{"type":"string","format":"uuid"}
        },
        "comparisonMode":{
          "type":"string",
          "enum":["auto","contract","policy","version"],
          "default":"auto",
          "title":"对比模式",
          "description":"自动识别文档类型，或按合同、制度、版本的重点维度进行对比。"
        },
        "instructions":{
          "type":"string",
          "maxLength":2000,
          "title":"补充对比要求",
          "description":"可选。说明需要重点关注的条款、制度要求、风险或版本变化。"
        }
      },
      "allOf":[
        {
          "if":{"required":["baselineDocument"]},
          "then":{
            "properties":{
              "comparisonDocuments":{"minItems":1,"maxItems":4}
            }
          },
          "else":{
            "properties":{
              "comparisonDocuments":{"minItems":2,"maxItems":5}
            }
          }
        }
      ],
      "additionalProperties":false
    }
    $json$::jsonb,
    $json$
    {
      "order":[
        "baselineDocument",
        "comparisonDocuments",
        "comparisonMode",
        "instructions"
      ],
      "widgets":{
        "baselineDocument":"file",
        "comparisonDocuments":"file",
        "comparisonMode":"segmented",
        "instructions":"textarea"
      },
      "enumLabels":{
        "comparisonMode":{
          "auto":"自动识别",
          "contract":"合同对比",
          "policy":"制度对比",
          "version":"版本对比"
        }
      },
      "fieldOptions":{
        "baselineDocument":{
          "acceptedMimeTypes":[
            "application/pdf",
            "application/msword",
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "application/vnd.ms-excel",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "application/vnd.ms-powerpoint",
            "application/vnd.openxmlformats-officedocument.presentationml.presentation",
            "text/plain",
            "text/markdown",
            "text/csv",
            "application/json",
            "application/zip",
            "application/octet-stream"
          ],
          "allowedExtensions":[
            ".pdf",".doc",".docx",".xls",".xlsx",".ppt",".pptx",
            ".txt",".md",".csv",".json"
          ],
          "maxItems":1,
          "maxFileSizeBytes":52428800,
          "maxTotalSizeBytes":52428800,
          "allowAssetLibrarySelection":true,
          "uploadLabel":"选择基准文档"
        },
        "comparisonDocuments":{
          "acceptedMimeTypes":[
            "application/pdf",
            "application/msword",
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "application/vnd.ms-excel",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "application/vnd.ms-powerpoint",
            "application/vnd.openxmlformats-officedocument.presentationml.presentation",
            "text/plain",
            "text/markdown",
            "text/csv",
            "application/json",
            "application/zip",
            "application/octet-stream"
          ],
          "allowedExtensions":[
            ".pdf",".doc",".docx",".xls",".xlsx",".ppt",".pptx",
            ".txt",".md",".csv",".json"
          ],
          "maxItems":5,
          "itemCountByFieldPresence":{
            "field":"baselineDocument",
            "present":{"minItems":1,"maxItems":4},
            "absent":{"minItems":2,"maxItems":5}
          },
          "maxFileSizeBytes":52428800,
          "maxTotalSizeBytes":209715200,
          "allowAssetLibrarySelection":true,
          "uploadLabel":"选择对比文档"
        },
        "comparisonMode":{
          "showSelectedIcon":false,
          "compact":true,
          "labelMaxLines":1
        }
      },
      "fieldHelp":{
        "baselineDocument":{
          "text":"基准文档可不上传；DOCX 和 PDF 基准文档可在结果页导出标注副本。"
        },
        "comparisonDocuments":{
          "text":"有基准文档时最多 4 份，无基准文档时最多 5 份；全部文件合计不能超过 200 MB。"
        }
      },
      "modelSelectionGroups":[
        {
          "key":"documentComparisonModel",
          "label":"文档对比模型",
          "description":"正文比较和扫描页理解使用同一模型家族。",
          "capabilities":["TEXT_GENERATION","VISION"],
          "options":[
            {
              "value":"gpt-5.6-sol",
              "displayName":"GPT-5.6 Sol",
              "description":"默认模型，适合复杂合同、制度和长文档版本对比。",
              "deployments":{
                "TEXT_GENERATION":"codex2api-gpt-5-6-sol-text",
                "VISION":"codex2api-gpt-5-6-sol-vision"
              }
            },
            {
              "value":"gpt-5.4-mini",
              "displayName":"GPT-5.4 Mini",
              "description":"响应更轻量，适合结构清晰的常规文档对比。",
              "deployments":{
                "TEXT_GENERATION":"codex2api-gpt-5-4-mini-text",
                "VISION":"codex2api-gpt-5-4-mini-vision"
              }
            }
          ]
        }
      ],
      "feeNotice":"文档解析、扫描页识别、多轮差异归纳和风险分析可能产生模型费用。点击“开始对比”即表示确认本次调用。",
      "submitLabel":"开始对比",
      "revisionSubmitLabel":"生成新对比版本"
    }
    $json$::jsonb,
    $json$
    {
      "$schema":"https://json-schema.org/draft/2020-12/schema",
      "type":"object",
      "required":[
        "format","mode","detectedMode","hasBaseline","reportMarkdown",
        "documents","pairwiseComparisons","crossDocumentConclusion",
        "risks","citations","warnings"
      ],
      "properties":{
        "format":{"const":"document_comparison"},
        "mode":{
          "type":"string",
          "enum":["auto","contract","policy","version"]
        },
        "detectedMode":{
          "type":"string",
          "enum":["contract","policy","version","general"]
        },
        "hasBaseline":{"type":"boolean"},
        "reportMarkdown":{"type":"string","minLength":1},
        "documents":{
          "type":"array",
          "minItems":2,
          "maxItems":5,
          "items":{"$ref":"#/$defs/document"}
        },
        "pairwiseComparisons":{
          "type":"array",
          "maxItems":4,
          "items":{"$ref":"#/$defs/pairwiseComparison"}
        },
        "crossDocumentConclusion":{
          "$ref":"#/$defs/crossDocumentConclusion"
        },
        "risks":{
          "type":"array",
          "items":{"$ref":"#/$defs/risk"}
        },
        "citations":{
          "type":"array",
          "items":{"$ref":"#/$defs/citation"}
        },
        "warnings":{
          "type":"array",
          "items":{"type":"string","maxLength":500}
        },
        "excelAssetId":{"type":"string","format":"uuid"},
        "annotatedBaselineAssetId":{"type":"string","format":"uuid"},
        "annotatedBaselineFormat":{
          "type":"string",
          "enum":["docx","pdf"]
        }
      },
      "$defs":{
        "document":{
          "type":"object",
          "required":["assetId","fileName","role"],
          "properties":{
            "assetId":{"type":"string","format":"uuid"},
            "fileName":{"type":"string","minLength":1,"maxLength":500},
            "role":{"type":"string","enum":["baseline","comparison"]}
          },
          "additionalProperties":false
        },
        "difference":{
          "type":"object",
          "required":[
            "topic","baselineContent","comparisonContent","impact",
            "changeType","citationMarkers"
          ],
          "properties":{
            "topic":{"type":"string","minLength":1,"maxLength":500},
            "baselineContent":{"type":"string"},
            "comparisonContent":{"type":"string"},
            "impact":{"type":"string","minLength":1},
            "changeType":{
              "type":"string",
              "enum":["added","deleted","modified","same","uncertain"]
            },
            "citationMarkers":{
              "type":"array",
              "minItems":2,
              "uniqueItems":true,
              "items":{"type":"string","pattern":"^S[1-9][0-9]*$"}
            }
          },
          "additionalProperties":false
        },
        "pairwiseComparison":{
          "type":"object",
          "required":[
            "comparisonAssetId","comparisonFileName","summary","differences"
          ],
          "properties":{
            "comparisonAssetId":{"type":"string","format":"uuid"},
            "comparisonFileName":{"type":"string","minLength":1,"maxLength":500},
            "summary":{"type":"string","minLength":1},
            "differences":{
              "type":"array",
              "items":{"$ref":"#/$defs/difference"}
            }
          },
          "additionalProperties":false
        },
        "documentStatement":{
          "type":"object",
          "required":["assetId","fileName","content","citationMarkers"],
          "properties":{
            "assetId":{"type":"string","format":"uuid"},
            "fileName":{"type":"string","minLength":1,"maxLength":500},
            "content":{"type":"string"},
            "citationMarkers":{
              "type":"array",
              "minItems":1,
              "uniqueItems":true,
              "items":{"type":"string","pattern":"^S[1-9][0-9]*$"}
            }
          },
          "additionalProperties":false
        },
        "consensusFinding":{
          "type":"object",
          "required":[
            "topic","documentStatements","commonality","difference",
            "impact","citationMarkers"
          ],
          "properties":{
            "topic":{"type":"string","minLength":1,"maxLength":500},
            "documentStatements":{
              "type":"array",
              "minItems":2,
              "items":{"$ref":"#/$defs/documentStatement"}
            },
            "commonality":{"type":"string"},
            "difference":{"type":"string"},
            "impact":{"type":"string","minLength":1},
            "citationMarkers":{
              "type":"array",
              "minItems":2,
              "uniqueItems":true,
              "items":{"type":"string","pattern":"^S[1-9][0-9]*$"}
            }
          },
          "additionalProperties":false
        },
        "crossDocumentConclusion":{
          "type":"object",
          "required":["summary","findings"],
          "properties":{
            "summary":{"type":"string","minLength":1},
            "findings":{
              "type":"array",
              "items":{"$ref":"#/$defs/consensusFinding"}
            }
          },
          "additionalProperties":false
        },
        "risk":{
          "type":"object",
          "required":[
            "severity","title","basis","recommendation",
            "affectedAssetIds","citationMarkers"
          ],
          "properties":{
            "severity":{"type":"string","enum":["HIGH","MEDIUM","LOW"]},
            "title":{"type":"string","minLength":1,"maxLength":500},
            "basis":{"type":"string","minLength":1},
            "recommendation":{"type":"string","minLength":1},
            "affectedAssetIds":{
              "type":"array",
              "minItems":1,
              "uniqueItems":true,
              "items":{"type":"string","format":"uuid"}
            },
            "citationMarkers":{
              "type":"array",
              "minItems":1,
              "uniqueItems":true,
              "items":{"type":"string","pattern":"^S[1-9][0-9]*$"}
            }
          },
          "additionalProperties":false
        },
        "citation":{
          "type":"object",
          "required":["marker","assetId","fileName","excerpt","locator"],
          "properties":{
            "marker":{"type":"string","pattern":"^S[1-9][0-9]*$"},
            "assetId":{"type":"string","format":"uuid"},
            "fileName":{"type":"string","minLength":1,"maxLength":500},
            "excerpt":{"type":"string","minLength":1,"maxLength":600},
            "locator":{
              "oneOf":[
                {
                  "type":"object",
                  "required":["type","pageNumber"],
                  "properties":{
                    "type":{"const":"PDF_PAGE"},
                    "pageNumber":{"type":"integer","minimum":1}
                  },
                  "additionalProperties":false
                },
                {
                  "type":"object",
                  "required":["type","paragraphStart","paragraphEnd"],
                  "properties":{
                    "type":{"const":"WORD_PARAGRAPH"},
                    "paragraphStart":{"type":"integer","minimum":1},
                    "paragraphEnd":{"type":"integer","minimum":1},
                    "heading":{"type":"string","maxLength":500},
                    "visual":{"type":"boolean"}
                  },
                  "additionalProperties":false
                },
                {
                  "type":"object",
                  "required":["type","sheetName","startRow","endRow"],
                  "properties":{
                    "type":{"const":"EXCEL_ROWS"},
                    "sheetName":{"type":"string","minLength":1,"maxLength":255},
                    "startRow":{"type":"integer","minimum":1},
                    "endRow":{"type":"integer","minimum":1},
                    "chartIndex":{"type":"integer","minimum":1}
                  },
                  "additionalProperties":false
                },
                {
                  "type":"object",
                  "required":["type","slideNumber"],
                  "properties":{
                    "type":{"const":"PPT_SLIDE"},
                    "slideNumber":{"type":"integer","minimum":1}
                  },
                  "additionalProperties":false
                },
                {
                  "type":"object",
                  "required":["type","startLine","endLine"],
                  "properties":{
                    "type":{"const":"TEXT_LINES"},
                    "startLine":{"type":"integer","minimum":1},
                    "endLine":{"type":"integer","minimum":1}
                  },
                  "additionalProperties":false
                }
              ]
            }
          },
          "additionalProperties":false
        }
      },
      "additionalProperties":false
    }
    $json$::jsonb,
    $json$
    {
      "modelAliases":{
        "TEXT_GENERATION":"text.document-compare",
        "VISION":"vision.document-compare"
      },
      "maxFiles":5,
      "maxFileSizeBytes":52428800,
      "maxTotalSizeBytes":209715200,
      "maxInstructionsLength":2000,
      "maxEvidenceChunksPerDocument":10,
      "taskTitleFromAssets":{
        "baselineField":"baselineDocument",
        "comparisonField":"comparisonDocuments",
        "baselineTemplate":"{name} 多文档对比",
        "comparisonTemplate":"{name} 等 {count} 份文档对比"
      },
      "capabilities":["TEXT_GENERATION","VISION"]
    }
    $json$::jsonb,
    now()
);

insert into feature_model_policy (
    id,
    feature_code,
    capability,
    default_deployment_code,
    allow_user_selection,
    created_at,
    updated_at
) values
    (
        'f201bbe2-0f34-415a-809e-ac332c10dec0',
        'document.compare',
        'TEXT_GENERATION',
        'codex2api-gpt-5-6-sol-text',
        true,
        now(),
        now()
    ),
    (
        'cddb2d2e-2edb-489f-98d9-c62a59ef2368',
        'document.compare',
        'VISION',
        'codex2api-gpt-5-6-sol-vision',
        true,
        now(),
        now()
    );

insert into feature_model_option (
    policy_id,
    deployment_code,
    display_name,
    description,
    sort_order,
    enabled
) values
    (
        'f201bbe2-0f34-415a-809e-ac332c10dec0',
        'codex2api-gpt-5-6-sol-text',
        'GPT-5.6 Sol',
        '质量优先，适合复杂合同、制度和长文档差异归纳。',
        10,
        true
    ),
    (
        'f201bbe2-0f34-415a-809e-ac332c10dec0',
        'codex2api-gpt-5-4-mini-text',
        'GPT-5.4 Mini',
        '速度和成本优先，适合结构清晰的常规文档对比。',
        20,
        true
    ),
    (
        'cddb2d2e-2edb-489f-98d9-c62a59ef2368',
        'codex2api-gpt-5-6-sol-vision',
        'GPT-5.6 Sol',
        '质量优先的扫描页、图表和复杂版面理解模型。',
        10,
        true
    ),
    (
        'cddb2d2e-2edb-489f-98d9-c62a59ef2368',
        'codex2api-gpt-5-4-mini-vision',
        'GPT-5.4 Mini',
        '速度和成本优先的扫描页与常规版面理解模型。',
        20,
        true
    );
