insert into feature_definition (
    id,
    workspace_id,
    code,
    display_name,
    description,
    status,
    current_version,
    result_type,
    renderer_key,
    execution_mode,
    sort_order,
    created_at,
    updated_at
)
select
    '1b1927e2-3cc1-42ab-9875-efba3fa7929b',
    workspace.id,
    'document.table_extraction',
    '表格与信息提取',
    '从单个 PDF、扫描件或图片中提取表格和字段，并输出 Excel 或 JSON 文件。',
    'INTERNAL',
    1,
    'file',
    'file',
    'ASYNC',
    20,
    now(),
    now()
from workspace
where workspace.code = 'document';

insert into feature_version (
    id,
    feature_id,
    version,
    input_schema_json,
    ui_schema_json,
    output_schema_json,
    config_json,
    created_at
) values (
    'a2d9c1df-0bdb-415e-a864-1074993ace8e',
    '1b1927e2-3cc1-42ab-9875-efba3fa7929b',
    1,
    $json$
    {
      "$schema":"https://json-schema.org/draft/2020-12/schema",
      "type":"object",
      "required":["document","extractionMode","outputFormat"],
      "properties":{
        "document":{
          "type":"string",
          "format":"uuid",
          "title":"待提取文件",
          "description":"每次处理一个 PDF 或图片。"
        },
        "extractionMode":{
          "type":"string",
          "enum":["auto","table","fields"],
          "default":"auto",
          "title":"提取模式",
          "description":"自动识别适合混合内容；也可以只提取表格或指定字段。"
        },
        "fieldNames":{
          "type":"string",
          "maxLength":3249,
          "title":"目标字段",
          "description":"每行填写一个字段名，最多 50 项。"
        },
        "outputFormat":{
          "type":"string",
          "enum":["xlsx","json"],
          "default":"xlsx",
          "title":"输出格式"
        },
        "instructions":{
          "type":"string",
          "maxLength":2000,
          "title":"补充或纠正要求",
          "description":"可选。说明表头、字段含义或需要纠正的识别结果。"
        }
      },
      "allOf":[
        {
          "if":{
            "properties":{"extractionMode":{"const":"fields"}},
            "required":["extractionMode"]
          },
          "then":{
            "required":["fieldNames"],
            "properties":{"fieldNames":{"minLength":1}}
          }
        }
      ],
      "additionalProperties":false
    }
    $json$::jsonb,
    $json$
    {
      "order":["document","extractionMode","fieldNames","outputFormat","instructions"],
      "widgets":{
        "document":"file",
        "extractionMode":"segmented",
        "fieldNames":"textarea",
        "outputFormat":"segmented",
        "instructions":"textarea"
      },
      "visibility":{
        "fieldNames":{"field":"extractionMode","equals":"fields"}
      },
      "enumLabels":{
        "extractionMode":{
          "auto":"自动识别",
          "table":"提取表格",
          "fields":"提取字段"
        },
        "outputFormat":{
          "xlsx":"Excel",
          "json":"JSON"
        }
      },
      "fieldOptions":{
        "document":{
          "acceptedMimeTypes":[
            "application/pdf",
            "image/jpeg",
            "image/png",
            "image/webp",
            "application/octet-stream"
          ],
          "allowedExtensions":[".pdf",".jpg",".jpeg",".png",".webp"],
          "maxItems":1,
          "maxFileSizeBytes":52428800,
          "maxTotalSizeBytes":52428800,
          "allowAssetLibrarySelection":true,
          "uploadLabel":"选择文件"
        },
        "extractionMode":{
          "showSelectedIcon":false,
          "compact":true,
          "labelMaxLines":1
        },
        "outputFormat":{
          "showSelectedIcon":false,
          "compact":true,
          "labelMaxLines":1
        }
      },
      "fieldHelp":{
        "document":{
          "text":"支持 PDF、JPG、JPEG、PNG 和 WebP；单文件最多 50 MB，PDF 最多 100 页。扫描 PDF 会按页调用所选模型的视觉能力。"
        },
        "fieldNames":{
          "text":"每行一个字段名，最多 50 项，每项最多 64 个字符。未找到的字段会标记为“无法识别”。"
        }
      },
      "modelSelectionGroups":[
        {
          "key":"documentExtractionModel",
          "label":"文档提取模型",
          "description":"页面识别和结构修复使用同一模型家族。",
          "capabilities":["TEXT_GENERATION","VISION"],
          "options":[
            {
              "value":"gpt-5.6-sol",
              "displayName":"GPT-5.6 Sol",
              "description":"默认模型，适合扫描件、复杂表格和合并单元格。",
              "deployments":{
                "TEXT_GENERATION":"codex2api-gpt-5-6-sol-text",
                "VISION":"codex2api-gpt-5-6-sol-vision"
              }
            },
            {
              "value":"gpt-5.4-mini",
              "displayName":"GPT-5.4 Mini",
              "description":"响应更轻量，适合结构清晰的常规表格和票据。",
              "deployments":{
                "TEXT_GENERATION":"codex2api-gpt-5-4-mini-text",
                "VISION":"codex2api-gpt-5-4-mini-vision"
              }
            }
          ]
        }
      ],
      "feeNotice":"表格与信息提取会调用所选付费模型。PDF 将按页分批识别，页数越多调用次数和费用可能越高；点击“开始提取”即表示确认本次调用。",
      "submitLabel":"开始提取",
      "revisionSubmitLabel":"生成纠正版"
    }
    $json$::jsonb,
    $json$
    {
      "$schema":"https://json-schema.org/draft/2020-12/schema",
      "type":"object",
      "required":[
        "assetId",
        "format",
        "name",
        "extractionMode",
        "tableCount",
        "fieldCount",
        "sourcePages",
        "confidence",
        "warnings",
        "partial"
      ],
      "properties":{
        "assetId":{"type":"string","format":"uuid"},
        "format":{"type":"string","enum":["xlsx","json"]},
        "name":{"type":"string","minLength":1,"maxLength":500},
        "extractionMode":{"type":"string","enum":["auto","table","fields"]},
        "tableCount":{"type":"integer","minimum":0},
        "fieldCount":{"type":"integer","minimum":0},
        "sourcePages":{
          "type":"array",
          "uniqueItems":true,
          "items":{"type":"integer","minimum":1}
        },
        "confidence":{"type":"number","minimum":0,"maximum":1},
        "warnings":{
          "type":"array",
          "items":{"type":"string","maxLength":500}
        },
        "partial":{"type":"boolean"}
      },
      "additionalProperties":false
    }
    $json$::jsonb,
    $json$
    {
      "modelAliases":{
        "TEXT_GENERATION":"text.document-table-extraction",
        "VISION":"vision.document-table-extraction"
      },
      "maxFiles":1,
      "maxFileSizeBytes":52428800,
      "maxPdfPages":100,
      "maxFieldCount":50,
      "maxInstructionsLength":2000,
      "pdfVisionBatchSize":8,
      "capabilities":["TEXT_GENERATION","VISION"]
    }
    $json$::jsonb,
    now()
);

insert into feature_model_policy (
    id,
    feature_code,
    capability,
    default_deployment_code,
    allow_user_selection,
    created_at,
    updated_at
) values
    (
        'bdac6f1c-e34d-4a36-90c2-3d46dbc7c957',
        'document.table_extraction',
        'TEXT_GENERATION',
        'codex2api-gpt-5-6-sol-text',
        true,
        now(),
        now()
    ),
    (
        '24acc4e9-057e-4f84-b8be-adbe72a2f7a7',
        'document.table_extraction',
        'VISION',
        'codex2api-gpt-5-6-sol-vision',
        true,
        now(),
        now()
    );

insert into feature_model_option (
    policy_id,
    deployment_code,
    display_name,
    description,
    sort_order,
    enabled
) values
    (
        'bdac6f1c-e34d-4a36-90c2-3d46dbc7c957',
        'codex2api-gpt-5-6-sol-text',
        'GPT-5.6 Sol',
        '默认模型，负责使用同一模型家族修复结构化输出。',
        10,
        true
    ),
    (
        'bdac6f1c-e34d-4a36-90c2-3d46dbc7c957',
        'codex2api-gpt-5-4-mini-text',
        'GPT-5.4 Mini',
        '轻量模型，负责使用同一模型家族修复结构化输出。',
        20,
        true
    ),
    (
        '24acc4e9-057e-4f84-b8be-adbe72a2f7a7',
        'codex2api-gpt-5-6-sol-vision',
        'GPT-5.6 Sol',
        '适合扫描件、复杂表格、合并单元格和票据字段识别。',
        10,
        true
    ),
    (
        '24acc4e9-057e-4f84-b8be-adbe72a2f7a7',
        'codex2api-gpt-5-4-mini-vision',
        'GPT-5.4 Mini',
        '适合结构清晰的常规表格和票据识别。',
        20,
        true
    );
